/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Fri Nov 17 18:10:12 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkModuleBOCfloat8_1_5_2_h__
#define __mkModuleBOCfloat8_1_5_2_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkModuleBOCfloat8_1_5_2 module */
class MOD_mkModuleBOCfloat8_1_5_2 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_mkModuleBOCfloat8_1_5_2(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt8 METH_bo_divide_m(tUInt8 ARG_bo_divide_m_xx, tUInt8 ARG_bo_divide_m_yy);
  tUInt8 METH_RDY_bo_divide_m();
  tUInt8 METH_bo_multiply_m(tUInt8 ARG_bo_multiply_m_xx, tUInt8 ARG_bo_multiply_m_yy);
  tUInt8 METH_RDY_bo_multiply_m();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkModuleBOCfloat8_1_5_2 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkModuleBOCfloat8_1_5_2 &backing);
};

#endif /* ifndef __mkModuleBOCfloat8_1_5_2_h__ */
