/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Dec 10 05:29:29 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkTb_h__
#define __mkTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkModuleBOCfloat8_1_4_3.h"
#include "mkModuleBOCfloat8_1_5_2.h"


/* Class declaration for the mkTb module */
class MOD_mkTb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkModuleBOCfloat8_1_4_3 INST_ifc;
  MOD_mkModuleBOCfloat8_1_5_2 INST_ifc2;
 
 /* Constructor */
 public:
  MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF_signed_4___d21;
  tUInt32 DEF_signed_3___d20;
  tUInt32 DEF_signed_2___d19;
  tUInt32 DEF_signed_1___d18;
  tUInt32 DEF_signed_0___d17;
 
 /* Rules */
 public:
  void RL_finishdis1();
  void RL_theUltimateAnswer();
  void RL_theUltimateAnswer2();
  void RL_displayrule2();
  void RL_displayrule3();
  void RL_displayrule2a();
  void RL_displayrule3a();
  void RL_displayrule3b();
  void RL_displayrule3c();
  void RL_displayrule2aa();
  void RL_displayrule3aa();
  void RL_displayrule2ab();
  void RL_displayrule3ab();
  void RL_displayrule3bc();
  void RL_displayrule3cd();
  void RL_finishdis2();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
};

#endif /* ifndef __mkTb_h__ */
